#Database
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

mongodb:
  casino-services-db:
    host: 127.0.0.1
    port: 27017
    database: casino-services-db
